<?php

namespace AppBundle\Repository;

/**
 * PaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReservationPayment($reservationId)
    {

        return $this ->createQueryBuilder('l')
            ->select('p')
            ->from('AppBundle:Payment','p')
            ->where('p.reservation = :reservation')
            ->setParameter('reservation', $reservationId)
            ->orderBy('p.created', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }


    public function findPayment($reservationId)
    {

        return $this ->createQueryBuilder('l')
            ->select('p')
            ->from('AppBundle:Payment','p')
            ->where('p.reservation = :reservation')
            ->setParameter('reservation', $reservationId)
            ->orderBy('p.created', 'DESC')
            ->getQuery()
            ->getSingleResult();
    }

}
