imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en





framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~



web_profiler:
    toolbar: true
    intercept_redirects: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        user_manager: pugx_user_manager
        mailer: fos_user.mailer.twig_swift


    resetting:
        email:
            template:   email/password_resetting.email.twig

    registration:
        confirmation:
            enabled: false
            template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address:        akoh.chuma@gmail.com
                sender_name:    Demo Registration






pugx_multi_user:
    users:
      participant:
          entity:
            class: AppBundle\Entity\Participant
          registration:
            form:
              type: AppBundle\Form\Type\ParticipantType
              name: fos_user_registration_form
              validation_groups:  [Registration, Default]
            #template: AppBundle:Registration:participant.form.html.twig
          profile:
            form:
              type: AppBundle\Form\Type\ProfileParticipantType

      developer:
              entity:
                class: AppBundle\Entity\Developer
              registration:
                form:
                  type: AppBundle\Form\Type\DeveloperType
                template: FOSUserBundle:Registration:landlord.html.twig
              profile:
                form:
                  type: AppBundle\Form\Type\ProfileDeveloperType


      support:
           entity:
             class: AppBundle\Entity\Support
           registration:
             form:
               type: AppBundle\Form\Type\SuportType
           profile:
              form:
               type: AppBundle\Form\Type\ProfileSupportType



# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci



        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }






assetic:
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~
        cssrewrite: ~



vich_uploader:
    db_driver: orm
    mappings:
             lease_agreement:
                uri_prefix:         /uploads/document/
                upload_destination: %kernel.root_dir%/../web/uploads/document/

                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true
                namer:              vich_uploader.namer_uniqid

             tenancy_agreement:
                 uri_prefix:         /uploads/document
                 upload_destination: %kernel.root_dir%/../web/uploads/document

                 inject_on_load:     false
                 delete_on_update:   true
                 delete_on_remove:   true
                 namer:              vich_uploader.namer_uniqid

