# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:

        ROLE_USER:           []
        ROLE_STAFF:          [ROLE_USER]

        ROLE_SURVEYOR:       [ROLE_STAFF]

        ROLE_TENANT:         [ROLE_USER]
        ROLE_LANDLORD:       [ROLE_USER]


        ROLE_DEVELOPER: [ROLE_USER]

        ROLE_DEVELOPER_ADMIN:
          - ROLE_DEVELOPER
          - ROLE_ALLOWED_TO_SWITCH

        ROLE_ADMIN:
          - ROLE_STAFF

        ROLE_SUPER_ADMIN:
          - ROLE_ADMIN
          - ROLE_SURVEYOR
          - ROLE_ALLOWED_TO_SWITCH



    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
#remember to change role admin back
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
